### ISSUE TITLE
Questions about `createFromBuffer`

### ISSUE THREAD

**Issue by filipebraida** [batosai/adonis-attachment#5]
I have a question about the API. When I create a file externally, the idea is to use the `attachmentManager.createFromBuffer` function. However, this function expects me to manually add the file using the drive, right?

This is considering the case of the `attachmentManager.createFromFile(file)` function.

Thanks again!

**Comment by batosai** [comment]
Hello, `createFromBuffer` waits for a Buffer object in the first argument and a second name. You have to turn the external file into a buffer to switch it to the method.

I have in my todo the creation of a new method for extern files. But for the time being, you've got to go through `createFromBuffer`.

**Comment by filipebraida** [comment]
No problem! I just wanted to confirm.
I ended up creating a function that generates the buffer and uses the drive's put method to upload the file.
